os:
  - linux
  - windows

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git config --global core.autocrlf input; fi

notifications:
  slack:
    secure: Fdl/sQMTl86jYN1r1CRRRQRgyFoslvrhkkfnM2JSdx4gODPgyg4nCPSKtU5j9wpSbbkq9A+YBeFv+Suh+xYNviegqa0AZbztydfFzVDS7xw43B/uR9Y4LwaP5Kis1WGuIOHawwFISNO3hTUei6aybKiKKlxvfqrARJaO01+Xxrg=
